import = ["~/.config/alacritty/vesper.toml"]

[font]
size = 16

[font.normal]
family = "FiraCode Nerd Font"

[shell]
args = ["--login"]
program = "/bin/zsh"

[[hints.enabled]]
command = "open"
hyperlinks = true
mouse.enabled = true
mouse.mods = "Super"
post_processing = true
persist = false
regex = "(ipfs:|ipns:|magnet:|mailto:|gemini://|gopher://|https://|http://|news:|file:|git://|ssh:|ftp://)[^\u0000-\u001F\u007F-\u009F<>\"\\s{-}\\^⟨⟩‘]+"

[window]
padding.x = 5
padding.y = 5

decorations = "Buttonless"

option_as_alt = "Both"


[keyboard]
[[keyboard.bindings]]
key = "Left"
mods = "Control"
chars = "\u0001"

[[keyboard.bindings]]
key = "Right"
mods = "Control"
chars = "\u0005"

[[keyboard.bindings]]
key = "Left"
mods = "Option"
chars = "\u001bf"


[[keyboard.bindings]]
key = "Right"
mods = "Option"
chars = "\u001bb"
