[[battery.display]]
threshold = 10
style = "red"

[[battery.display]]
threshold = 50
style = "yellow"

[kubernetes]
disabled = false

[kubernetes.context_aliases]
"arn:.*/(?P<cluster_name>[\\w-]+)" = "aws-$cluster_name"

[memory_usage]
disabled = false
threshold = -1
style = "bright-green"

[time]
disabled = false
style = "white"
