[manager]
show_hidden = true

[[manager.prepend_keymap]]
on = "o"
run = "plugin open-with-cmd --args=block"
desc = "Open with command in the terminal"

[[manager.prepend_keymap]]
on = "O"
run = "plugin open-with-cmd"
desc = "Open with command"

[opener]
edit = [
  { run = 'cursor "$0"', block = true },
  { run = 'nvim "$0"', block = true },
]
