#!/bin/bash

# Bash completion v2
[[ -r "/usr/local/etc/profile.d/bash_completion.sh" ]] && . "/usr/local/etc/profile.d/bash_completion.sh"

# k8s alias and auto complete
source <(kubectl completion bash)
alias k=kubectl
complete -F __start_kubectl k
export do="--dry-run=client -o yaml"

# watch
alias watch='watch '
